plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.notiq'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.kafka:spring-kafka:3.3.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'

    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
publishing {
    publications {
        mavenJava(MavenPublication){
            from components.java

            groupId='com.notiq'
            artifactId='notiq-event-producer'
            version='1.0-SNAPSHOT'
        }
    }
}