package com.notiq.emailservice.service;

import com.notiq.emailservice.sender.EmailSender;
import com.notiq.eventproducer.dto.NotificationEvent;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class EmailService {
    private final EmailSender emailSender;
    public void process(NotificationEvent event){
        String subject=buildSubject(event);
        String body=buildBody(event);
        emailSender.send(event,subject,body);
    }
    private String buildSubject(NotificationEvent event){
        return switch(event.getEventType()){
             case USER_REGISTERED->"Welcome to Notiq";
            default -> "Notification from notiq";
        };
    }
    private String buildBody(NotificationEvent event){
        return """
                Hello,
                This notification was generated by Notiq,
                Event Id: %s,
                Event Type: %s,
                Regards,
                Notiq 
                """.formatted(event.getEventId(),event.getEventType());
    }
}
