package com.notiq.emailservice.service;

import com.notiq.emailservice.sender.EmailSender;
import com.notiq.eventproducer.dto.NotificationEvent;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class EmailService {
    private final EmailSender emailSender;
    public void process(NotificationEvent event){
        String subject=buildSubject(event);
        String body=buildBody(event);
        emailSender.send(event,subject,body);
    }
    private String buildSubject(NotificationEvent event){
        return "Notification from Notiq Playground";//alter the subject based on the Event Type.For eg: if the eventType is User_Registered right to subject according to that.
    }
    private String buildBody(NotificationEvent event){
        return """
            Hello,

            Welcome to Notiq.

            This email was generated by Notiq, an event-driven notification platform built using Apache Kafka, Spring Boot, and PostgreSQL.

            Notiq demonstrates how modern notification systems can reliably process, track, and deliver notifications across distributed services while maintaining observability and fault tolerance.

            Notification Details
            --------------------
            Event ID       : %s
            Event Type     : %s
            Channel        : %s
            Priority       : %s
            Correlation ID : %s

            Payload
            -------
            %s

            Delivery Lifecycle
            ------------------
            RECEIVED → DISPATCHED → DELIVERED

            If delivery fails, Notiq automatically retries the notification up to 3 times before moving it to the Dead Letter Queue (DLQ) for further inspection.

            This message was sent as part of a demonstration of the Notiq platform.

            Regards,
            Notiq Team

            Event ID: %s
            """
                .formatted(
                        event.getEventId(),
                        event.getEventType(),
                        event.getChannel(),
                        event.getPriority(),
                        event.getCorrelationId(),
                        formatPayload(event),
                        event.getEventId()
                );
    }

    private String formatPayload(NotificationEvent event){
        if(event.getPayload() == null || event.getPayload().isEmpty()){
            return "No payload data available.";
        }

        StringBuilder sb = new StringBuilder();

        event.getPayload().forEach(
                (key, value) ->
                        sb.append("• ")
                                .append(key)
                                .append(" : ")
                                .append(value)
                                .append("\n")
        );

        return sb.toString();
    }
}
